/*
Tembo Cloud

Testing StackAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package temboclient

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "github.com/tembo-io/terraform-provider-tembo/temboclient"
)

func Test_temboclient_StackAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StackAPIService GetAllEntities", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.StackAPI.GetAllEntities(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StackAPIService GetEntity", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var type_ StackType

		resp, httpRes, err := apiClient.StackAPI.GetEntity(context.Background(), type_).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
