/*
Tembo Cloud

Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temboclient

import (
	"encoding/json"
)

// checks if the PgBouncer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PgBouncer{}

// PgBouncer PgBouncer is the type for the PGBouncer configuration
type PgBouncer struct {
	// Valid pgbouncer parameter values can be found at [https://www.pgbouncer.org/config.html](https://www.pgbouncer.org/config.html)
	Parameters map[string]string `json:"parameters,omitempty"`
	PoolMode *PoolerPgbouncerPoolMode `json:"poolMode,omitempty"`
	Resources NullablePoolerTemplateSpecContainersResources `json:"resources,omitempty"`
}

// NewPgBouncer instantiates a new PgBouncer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPgBouncer() *PgBouncer {
	this := PgBouncer{}
	return &this
}

// NewPgBouncerWithDefaults instantiates a new PgBouncer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPgBouncerWithDefaults() *PgBouncer {
	this := PgBouncer{}
	return &this
}

// GetParameters returns the Parameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PgBouncer) GetParameters() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PgBouncer) GetParametersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return &o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *PgBouncer) HasParameters() bool {
	if o != nil && IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]string and assigns it to the Parameters field.
func (o *PgBouncer) SetParameters(v map[string]string) {
	o.Parameters = v
}

// GetPoolMode returns the PoolMode field value if set, zero value otherwise.
func (o *PgBouncer) GetPoolMode() PoolerPgbouncerPoolMode {
	if o == nil || IsNil(o.PoolMode) {
		var ret PoolerPgbouncerPoolMode
		return ret
	}
	return *o.PoolMode
}

// GetPoolModeOk returns a tuple with the PoolMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PgBouncer) GetPoolModeOk() (*PoolerPgbouncerPoolMode, bool) {
	if o == nil || IsNil(o.PoolMode) {
		return nil, false
	}
	return o.PoolMode, true
}

// HasPoolMode returns a boolean if a field has been set.
func (o *PgBouncer) HasPoolMode() bool {
	if o != nil && !IsNil(o.PoolMode) {
		return true
	}

	return false
}

// SetPoolMode gets a reference to the given PoolerPgbouncerPoolMode and assigns it to the PoolMode field.
func (o *PgBouncer) SetPoolMode(v PoolerPgbouncerPoolMode) {
	o.PoolMode = &v
}

// GetResources returns the Resources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PgBouncer) GetResources() PoolerTemplateSpecContainersResources {
	if o == nil || IsNil(o.Resources.Get()) {
		var ret PoolerTemplateSpecContainersResources
		return ret
	}
	return *o.Resources.Get()
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PgBouncer) GetResourcesOk() (*PoolerTemplateSpecContainersResources, bool) {
	if o == nil {
		return nil, false
	}
	return o.Resources.Get(), o.Resources.IsSet()
}

// HasResources returns a boolean if a field has been set.
func (o *PgBouncer) HasResources() bool {
	if o != nil && o.Resources.IsSet() {
		return true
	}

	return false
}

// SetResources gets a reference to the given NullablePoolerTemplateSpecContainersResources and assigns it to the Resources field.
func (o *PgBouncer) SetResources(v PoolerTemplateSpecContainersResources) {
	o.Resources.Set(&v)
}
// SetResourcesNil sets the value for Resources to be an explicit nil
func (o *PgBouncer) SetResourcesNil() {
	o.Resources.Set(nil)
}

// UnsetResources ensures that no value is present for Resources, not even an explicit nil
func (o *PgBouncer) UnsetResources() {
	o.Resources.Unset()
}

func (o PgBouncer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PgBouncer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.PoolMode) {
		toSerialize["poolMode"] = o.PoolMode
	}
	if o.Resources.IsSet() {
		toSerialize["resources"] = o.Resources.Get()
	}
	return toSerialize, nil
}

type NullablePgBouncer struct {
	value *PgBouncer
	isSet bool
}

func (v NullablePgBouncer) Get() *PgBouncer {
	return v.value
}

func (v *NullablePgBouncer) Set(val *PgBouncer) {
	v.value = val
	v.isSet = true
}

func (v NullablePgBouncer) IsSet() bool {
	return v.isSet
}

func (v *NullablePgBouncer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePgBouncer(val *PgBouncer) *NullablePgBouncer {
	return &NullablePgBouncer{value: val, isSet: true}
}

func (v NullablePgBouncer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePgBouncer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


