/*
Tembo Cloud

Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temboclient

import (
	"encoding/json"
	"fmt"
)

// checks if the AppTypeOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppTypeOneOf3{}

// AppTypeOneOf3 struct for AppTypeOneOf3
type AppTypeOneOf3 struct {
	Embeddings NullableAppConfig `json:"embeddings"`
}

type _AppTypeOneOf3 AppTypeOneOf3

// NewAppTypeOneOf3 instantiates a new AppTypeOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppTypeOneOf3(embeddings NullableAppConfig) *AppTypeOneOf3 {
	this := AppTypeOneOf3{}
	this.Embeddings = embeddings
	return &this
}

// NewAppTypeOneOf3WithDefaults instantiates a new AppTypeOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppTypeOneOf3WithDefaults() *AppTypeOneOf3 {
	this := AppTypeOneOf3{}
	return &this
}

// GetEmbeddings returns the Embeddings field value
// If the value is explicit nil, the zero value for AppConfig will be returned
func (o *AppTypeOneOf3) GetEmbeddings() AppConfig {
	if o == nil || o.Embeddings.Get() == nil {
		var ret AppConfig
		return ret
	}

	return *o.Embeddings.Get()
}

// GetEmbeddingsOk returns a tuple with the Embeddings field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppTypeOneOf3) GetEmbeddingsOk() (*AppConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Embeddings.Get(), o.Embeddings.IsSet()
}

// SetEmbeddings sets field value
func (o *AppTypeOneOf3) SetEmbeddings(v AppConfig) {
	o.Embeddings.Set(&v)
}

func (o AppTypeOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppTypeOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["embeddings"] = o.Embeddings.Get()
	return toSerialize, nil
}

func (o *AppTypeOneOf3) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"embeddings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppTypeOneOf3 := _AppTypeOneOf3{}

	err = json.Unmarshal(bytes, &varAppTypeOneOf3)

	if err != nil {
		return err
	}

	*o = AppTypeOneOf3(varAppTypeOneOf3)

	return err
}

type NullableAppTypeOneOf3 struct {
	value *AppTypeOneOf3
	isSet bool
}

func (v NullableAppTypeOneOf3) Get() *AppTypeOneOf3 {
	return v.value
}

func (v *NullableAppTypeOneOf3) Set(val *AppTypeOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableAppTypeOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableAppTypeOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppTypeOneOf3(val *AppTypeOneOf3) *NullableAppTypeOneOf3 {
	return &NullableAppTypeOneOf3{value: val, isSet: true}
}

func (v NullableAppTypeOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppTypeOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


