/*
Tembo Cloud

Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temboclient

import (
	"encoding/json"
)

// checks if the PgConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PgConfig{}

// PgConfig struct for PgConfig
type PgConfig struct {
	Name string `json:"name"`
	Value string `json:"value"`
}

// NewPgConfig instantiates a new PgConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPgConfig(name string, value string) *PgConfig {
	this := PgConfig{}
	this.Name = name
	this.Value = value
	return &this
}

// NewPgConfigWithDefaults instantiates a new PgConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPgConfigWithDefaults() *PgConfig {
	this := PgConfig{}
	return &this
}

// GetName returns the Name field value
func (o *PgConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PgConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PgConfig) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *PgConfig) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PgConfig) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *PgConfig) SetValue(v string) {
	o.Value = v
}

func (o PgConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PgConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullablePgConfig struct {
	value *PgConfig
	isSet bool
}

func (v NullablePgConfig) Get() *PgConfig {
	return v.value
}

func (v *NullablePgConfig) Set(val *PgConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePgConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePgConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePgConfig(val *PgConfig) *NullablePgConfig {
	return &NullablePgConfig{value: val, isSet: true}
}

func (v NullablePgConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePgConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


