/*
Tembo Cloud

Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temboclient

import (
	"encoding/json"
)

// checks if the Autoscaling type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Autoscaling{}

// Autoscaling struct for Autoscaling
type Autoscaling struct {
	Autostop *AutoStop `json:"autostop,omitempty"`
	Storage *AutoscalingStorage `json:"storage,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Autoscaling Autoscaling

// NewAutoscaling instantiates a new Autoscaling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoscaling() *Autoscaling {
	this := Autoscaling{}
	return &this
}

// NewAutoscalingWithDefaults instantiates a new Autoscaling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoscalingWithDefaults() *Autoscaling {
	this := Autoscaling{}
	return &this
}

// GetAutostop returns the Autostop field value if set, zero value otherwise.
func (o *Autoscaling) GetAutostop() AutoStop {
	if o == nil || IsNil(o.Autostop) {
		var ret AutoStop
		return ret
	}
	return *o.Autostop
}

// GetAutostopOk returns a tuple with the Autostop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Autoscaling) GetAutostopOk() (*AutoStop, bool) {
	if o == nil || IsNil(o.Autostop) {
		return nil, false
	}
	return o.Autostop, true
}

// HasAutostop returns a boolean if a field has been set.
func (o *Autoscaling) HasAutostop() bool {
	if o != nil && !IsNil(o.Autostop) {
		return true
	}

	return false
}

// SetAutostop gets a reference to the given AutoStop and assigns it to the Autostop field.
func (o *Autoscaling) SetAutostop(v AutoStop) {
	o.Autostop = &v
}

// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *Autoscaling) GetStorage() AutoscalingStorage {
	if o == nil || IsNil(o.Storage) {
		var ret AutoscalingStorage
		return ret
	}
	return *o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Autoscaling) GetStorageOk() (*AutoscalingStorage, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *Autoscaling) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given AutoscalingStorage and assigns it to the Storage field.
func (o *Autoscaling) SetStorage(v AutoscalingStorage) {
	o.Storage = &v
}

func (o Autoscaling) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Autoscaling) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Autostop) {
		toSerialize["autostop"] = o.Autostop
	}
	if !IsNil(o.Storage) {
		toSerialize["storage"] = o.Storage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Autoscaling) UnmarshalJSON(data []byte) (err error) {
	varAutoscaling := _Autoscaling{}

	err = json.Unmarshal(data, &varAutoscaling)

	if err != nil {
		return err
	}

	*o = Autoscaling(varAutoscaling)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "autostop")
		delete(additionalProperties, "storage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAutoscaling struct {
	value *Autoscaling
	isSet bool
}

func (v NullableAutoscaling) Get() *Autoscaling {
	return v.value
}

func (v *NullableAutoscaling) Set(val *Autoscaling) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoscaling) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoscaling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoscaling(val *Autoscaling) *NullableAutoscaling {
	return &NullableAutoscaling{value: val, isSet: true}
}

func (v NullableAutoscaling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoscaling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


