/*
Tembo Data API

Testing SecretsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package tembodataclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_tembodataclient_SecretsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SecretsApiService GetSecret", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string
		var secretName string

		resp, httpRes, err := apiClient.SecretsApi.GetSecret(context.Background(), namespace, secretName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretsApiService GetSecretNames", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.SecretsApi.GetSecretNames(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretsApiService GetSecretNamesV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var instanceId string

		resp, httpRes, err := apiClient.SecretsApi.GetSecretNamesV1(context.Background(), orgId, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretsApiService GetSecretV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var instanceId string
		var secretName string

		resp, httpRes, err := apiClient.SecretsApi.GetSecretV1(context.Background(), orgId, instanceId, secretName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
